version: '3'

services:
  db:
    container_name: db_school
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 10pineappleAPPLE10
    ports:
      - "3306:3306"
    volumes:
      - db_data_school:/var/lib/mysql
      - $PWD/db_school:/docker-entrypoint-initdb.d
      - ../resource/tmp:/tmp

    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--secure-file-priv=','--local-infile=1']

  phpmyadmin:
    container_name: phpmyadmin_school
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 10pineappleAPPLE10
    depends_on:
      - db

volumes:
  db_data_school:
